// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCA5ZhURFgUuV1YoVnkOL69RU8C_eFsY',
    appId: '1:259439526042:web:2f71f4b50486076e7edf23',
    messagingSenderId: '259439526042',
    projectId: 'riskli-agac-takip',
    authDomain: 'riskli-agac-takip.firebaseapp.com',
    storageBucket: 'riskli-agac-takip.firebasestorage.app',
    measurementId: 'G-QCX50CQBP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9zEdAGuT3Ejw5unDJwL9XDtmqTVvTKxM',
    appId: '1:259439526042:android:a69b7d6fba4a10487edf23',
    messagingSenderId: '259439526042',
    projectId: 'riskli-agac-takip',
    storageBucket: 'riskli-agac-takip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9b0E-u_3RyjjobTjwQ2rfDcIUTOOJi_o',
    appId: '1:259439526042:ios:059e207a53678d287edf23',
    messagingSenderId: '259439526042',
    projectId: 'riskli-agac-takip',
    storageBucket: 'riskli-agac-takip.firebasestorage.app',
    iosBundleId: 'com.example.riskliAgacTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9b0E-u_3RyjjobTjwQ2rfDcIUTOOJi_o',
    appId: '1:259439526042:ios:059e207a53678d287edf23',
    messagingSenderId: '259439526042',
    projectId: 'riskli-agac-takip',
    storageBucket: 'riskli-agac-takip.firebasestorage.app',
    iosBundleId: 'com.example.riskliAgacTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkCA5ZhURFgUuV1YoVnkOL69RU8C_eFsY',
    appId: '1:259439526042:web:6cfe7934f1b90e097edf23',
    messagingSenderId: '259439526042',
    projectId: 'riskli-agac-takip',
    authDomain: 'riskli-agac-takip.firebaseapp.com',
    storageBucket: 'riskli-agac-takip.firebasestorage.app',
    measurementId: 'G-6YGCGNZWC6',
  );
}
